disabled_rules:
  - file_length
  - cyclomatic_complexity
  - function_body_length
  - type_body_length
  - multiple_closures_with_trailing_closure
  - blanket_disable_command
excluded:
  - .build
  - .dependencies
  - DerivedData
